# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
